import React from "react";

 export default [
    {
        id:1,
        title:"image1",src:"./images/image-1.jpg"
    },
    {
        id:2,
        title:"image2",src:"./images/image-2.jpg"
    },
    {
        id:3,
        title:"image3",src:"./images/image-10.jpg"
    },
    {
        id:4,
        title:"image4",src:"./images/image-4.jpg"
    },
    {
        id:5,
        title:"image5",src:"./images/image-5.jpg"
    },
    {
        id:6,
        title:"image6",src:"./images/image-6.jpg"
    },
    {
        id:7,
        title:"image7",src:"./images/image-7.jpg"
    },
    {
        id:8,
        title:"image8",src:"./images/image-8.jpg"
    },
    {
        id:9,
        title:"image9",src:"./images/image-9.jpg"
    }
]
